targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          namespaces: true
          string_interpolation: braces
          input_directory: assets/i18n
          output_directory: lib/i18n # defaulting to lib/gen if input is outside of lib/